name: cricket_player_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  get_it: ^7.6.0
  injectable: ^2.1.1

  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0

  sqflite: ^2.2.8
  path: ^1.8.3

  connectivity_plus: ^4.0.1

  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  dartz:
  cached_network_image:
  fl_chart:
  image_picker:
  image:
  shimmer:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.7.0
  build_runner: ^2.4.0
  injectable_generator: ^2.1.5



  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

